name: JMeter Stress Test

on:
  push: # Execute the workflow on each push to the repository
    branches:
      - main # Change this to your main branch name if different
  pull_request: # Execute the workflow on pull requests
    branches:
      - main # Change this to your main branch name if different

jobs:
  jmeter-stress-test:
    runs-on: ubuntu-latest # You can choose a different runner if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Change this to the desired Java version if needed

      - name: Install JMeter
        run: |
          wget -q https://downloads.apache.org//jmeter/binaries/apache-jmeter-X.XX.tgz
          tar -xzf apache-jmeter-X.XX.tgz
          export JMETER_HOME=$PWD/apache-jmeter-X.XX
          export PATH=$JMETER_HOME/bin:$PATH

      - name: Run JMeter Test
        run: jmeter -n -t exemplo.jmx -l results.jtl

      # Add additional steps to analyze the test results, like uploading artifacts or sending notifications.
